### ISSUE TITLE
huge drop of framerate when changing movement direction

### ISSUE THREAD

**Issue by ghost** [jasonisop/lpc_game#6]
When player is moving with arrow keys, sometimes when changing the movement direction there's a huge frame rate drop and a delay of sometimes up to a second, the player seems jumping several tiles afterwards.
Normally, when standing still or moving in one direction only, the frame rate is higher than 300fps.

My system is Debian Linux with a recent Intel graphics card, I use Löve 0.8.0 and lpc github  version of 11/Jun.

**Comment by jasonisop** [comment]
I'm going to be re-doing the camera/player code and this "should" fix the issues.
